{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.projectName }}-{{ .Values.environment }}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "django-api-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.projectName }}-{{ .Values.environment }}"
  {{ if eq .Values.environment "prod"}}
  minReplicas: 2
  maxReplicas: 10
  {{ else if eq .Values.environment "test"}}
  minReplicas: 1
  maxReplicas: 2
  {{ else }}
  minReplicas: 1
  maxReplicas: 3
  {{ end }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}

